name: Checkov IaC Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  checkov-scan:
    runs-on: ${{ 'ubuntu-latest' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Checkov
        run: |
          mkdir -p ./checkov
          /usr/bin/pip3 install checkov==2.5.0 --no-cache-dir -t ./checkov
          export PYTHONPATH=$PWD/checkov:$PYTHONPATH
        env:
          PYTHONPATH: $PWD/checkov

      - name: Run Checkov
        id: checkov
        run: |
          export PYTHONPATH=$PWD/checkov:$PYTHONPATH
          export PATH=$PWD/checkov/bin:$PATH
          ./checkov/bin/checkov -d . --skip-path ./checkov --framework terraform dockerfile kubernetes ansible --output cli --soft-fail
